# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fffc1c7375f9972153cb29b294cdb3c640f7908fbd78820108fcaea6318c9aca73ddb12354d769b943aea28b7cade75667e051a8decfaf5de28290538947211

test:
  secret_key_base: 04631b50d62436398d754070a327dd8c8859f682103317df6bfdd619f4da423221601464cefbd049ce2c67ecaaad27cf9213925a1791efe7971bba106f469570

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
